#'@title "DrawGraphML" :  Creates a XML file, describing "r" as a graph in GraphML format
#'
#'@description:  this function creates a XML file, describing "r" as a graph in GraphML format.
#'				 The nodes are the genes (for instance) and an edge A $\\rightarrow$ B reflects the action of node A on node B (amplification), 
#'			  	 while a dashed line (with a "T" arrow  betwwen A and B) reflects an inhibition of node B by node A.
#'				 The graph is a "valued oriented graph", and values, associated to edges, mean the "strength" of this action.
#'				 This file may be used directly by visualization tools, like Cytoscape, iGraph, Google Charts, Tableau, Grafana, Chartist.js, FusionCharts, Datawrapper, 
#'				 Infogram, ChartBlocks, and D3.js. These tools offer a variety of visualization styles, are easy to use, and can handle large data sets.
#'
#'@param  Ret	List or Matrix		list of informations delivered by "MRARegress" or square matrix of numbers.
#'									If 'Ret' is a list of informations delivered by "MRARegress", DrawGraphML uses 'Ret$r' (connectivity matrix) and 
#'								    'Ret$InputPar$NodeName' (name of the nodes).
#'									If 'Ret' is a square matrix, it corresponds to a connectivity matrix, and the names of the nodes are the names of the columns if defined,
#'									or a sequence of numbers if not.
#'@param  File	String				Name of the file to write. DrawGraphML adds the extension ".graphml" if necessary.
#'									If the file exists, an error is displayed and DrawGrahML stops.
#'@param  Thr	Number (>= 0)		A threshold to determine edge existence. Default value is 0.1.
#'									An edge is drawn between nodes 'i' and 'j' iff connectivity coefficient is >= Thr (ie \|MatrCc\[i,j\]\| >= Thr)
#'
#'@details	
#'		Imported libraries :
#'		- stringr				To use str_detect()
#'
#'	OUTPUT:
#'
#'		  XML		String					
#'					The name of the xml file created.
#'  	theGraph	List of dataframes 		
#'					nodes (list of nodes), edges (list of edges : source, target, interaction, value).
#'		Variables	List					
#'					list of important variables used by the program (Thr, nbN, nodesName, MatrCc)

#'@import	stringr
#'
#'
#'@name			DrawGraphML
#'
#'@description	Creates a XML file, describing "r" as a graph in GraphML format.
#'				The input data are described above and the outputs below.
#'
#'@return		List					NULL in case of error or a list of informations ("XML", "theGraph", "Variables").

#'@export
#'


DrawGraphML <- function (Ret, File, Thr=0.1) {
  tryCatch (
	expr = {
		cat ("START DrawGraphML !", as.character(Sys.time()), "\n")

		toReturn	<- list()			# Return values
		toReturn[["XML"]]		<- NULL
		toReturn[["theGraph"]]	<- NULL
		toReturn[["Variables"]]	<- NULL
		
		# Check input data
		err	<-  CheckInputDataDGML (Ret, File, Thr)
		if (! is.null(err)) {
			message (err)
			return (NULL)
		}

		# Check file
		if (! str_detect(File,".graphml"))
			File  <- paste(File, ".graphml", sep="")
		if (file.exists(File)) {
			message (paste("File ", File, " exists. \nUnable to create graphml file", sep=""))
			return (NULL)
		}

		# File header
		Conx <- file(File, open = "at")									# Creates the file
		writeLines ('<?xml version="1.0" encoding="UTF-8" standalone="no"?>', 	con=Conx)
		writeLines ('<graphml xmlns="http://graphml.graphdrawing.org/xmlns"', 	con=Conx) 
		writeLines ('\txmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',	con=Conx)
		writeLines ('\txsi:schemaLocation="http://graphml.graphdrawing.org/xmlns',con=Conx) 
		writeLines ('\thttp://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">',con=Conx)

		# Defining GraphML-Attribute Values  
		writeLines ('<key id="name" 		attr.name="name" 		attr.type="string" 	for="all"/>',	con=Conx)
		writeLines ('<key id="interaction"	attr.name="interaction" attr.type="string" 	for="edge"/>',	con=Conx)
		writeLines ('<key id="source"		attr.name="source" 		attr.type="string" 	for="edge" />',	con=Conx)
		writeLines ('<key id="target"		attr.name="target" 		attr.type="string" 	for="edge"/>',	con=Conx)
		writeLines ('<key id="value"		attr.name="value" 		attr.type="double" 	for="edge"/>',	con=Conx)
		writeLines ('<!--  Generated by MRARegress::DrawGraphML		-->',	con=Conx)	

		nn	<- paste ('<graph edgedefault="directed" id="', File, '">', sep="")
 		writeLines (nn,	con=Conx)
  
		# Variables declaration
		if (is.matrix(Ret)) {
			nbN			<- dim(Ret)[1]									# Number of nodes (nb. of rows)
			if (is.null (colnames(Ret))) {
				nodesName	<- as.character(seq(1:nbN))					# Name of the nodes
			} else {
				nodesName	<- colnames(Ret)							# Name of the nodes
			}
			MatrCc		<- Ret											# Connectivity matrix
		} else {
			nbN			<- Ret$Input$Variables$nbN						# Number of nodes (nb. of rows)
			nodesName	<- Ret$Input$InputPar$NodeName					# Name of the nodes
			MatrCc		<- Ret$r										# Connectivity matrix
		}

		source		<- NULL												# Source of the edges
		target		<- NULL												# Target of the edges
		interaction	<- NULL												# Source action on target : "d" : amplifies, "r" : inhibits
		value		<- NULL												# Action magnitude
		
		# Network construction
		nodes	<- data.frame(id=nodesName)								# List of the nodes
		diag(MatrCc)	<- 0
	
		for (jCol in 1:nbN) {
			for (iRow in 1:nbN) {
				if (abs(MatrCc[iRow,jCol]) < Thr)
					next
				source	<- c(source, nodesName[jCol])
				target	<- c(target, nodesName[iRow])
				value	<- c(value,  MatrCc[iRow,jCol] %>% round(3))
				if (MatrCc[iRow,jCol] > 0)
					interaction	<- c(interaction, "d")
				else
					interaction	<- c(interaction, "r")
			}
		}

		edges	<- data.frame(source=source, target=target, interaction=interaction, value=value, stringsAsFactors=FALSE)		# List of the edges

		#	GraphML file creation
		for (iNode in 1:nrow(nodes)) {
			nn	<- paste('\t\t<node id="', nodes$id[iNode], '"/>', sep="")
			writeLines (nn,	con=Conx)
		}

		for (iEdge in 1:nrow(edges)) {
			nn	<- 	paste('\t\t<edge id="e', iEdge, '" source="', edges$source[iEdge], '" target="', edges$target[iEdge], '">', sep="")
			writeLines (nn,	con=Conx)
           nn	<-	paste('\t\t\t<data key="name">', edges$source[iEdge], '(', edges$interaction[iEdge], ')', edges$target[iEdge], '</data>', sep="")
			writeLines (nn,	con=Conx)
           nn	<-	paste('\t\t\t<data key="interaction">', edges$interaction[iEdge], '</data>', sep="")
			writeLines (nn,	con=Conx)
           nn	<-	paste('\t\t\t<data key="source">', edges$source[iEdge], '</data>', sep="")
			writeLines (nn,	con=Conx)
           nn	<-	paste('\t\t\t<data key="target">', edges$target[iEdge], '</data>', sep="")
			writeLines (nn,	con=Conx)
           nn	<-	paste('\t\t\t<data key="value">', edges$value[iEdge], '</data>', sep="")
			writeLines (nn,	con=Conx)
			writeLines ("\t\t</edge>",	con=Conx)
		}
		
		writeLines ("\t</graph>",	con=Conx)
		writeLines ("</graphml>",	con=Conx)
		close(Conx)

		toReturn$XML		<- File
		toReturn$theGraph	<- list (nodes, edges)
		toReturn$Variables	<- list (Thr, nbN, MatrCc)
		
		cat ("DONE !", as.character(Sys.time()), "\n")
		return (toReturn)
	},		# expr
	
	warning = function (e) {
		message ("Warning detected !")
		print(e)	
		return (toReturn)
	},		# warning
	
	error = function (e) {
		message ("Error detected !")
		print(e)
	}		# error
  )			# tryCatch
  
  return (NULL)
}		# DrawGraphML


#' Checks the input data for function DrawGraphML
#'
#' This function checks the input data for function DrawGraphML.
#' The parameters are the same as those of DrawGraphML.
#'
#'@param Ret		list of informations delivered by "MRARegress" or a square matrix.
#'@param File		Name of the file to write.
#'@param Thr		Threshold to determine edge existence
#'

#'
#' @return 			A message if an error is detected and returns NULL otherwise.
#'

CheckInputDataDGML	<- function (Ret, File, Thr) {
  tryCatch (
	expr = {
		# Test input data : Ret or Matr
		if (is.matrix(Ret)) {
			if (dim(Ret)[1] != dim(Ret)[2])
				return ("If 'Ret' is a matrix, it must be a square matrix !")			
			if (! is.numeric(Ret))
				return ("If 'Ret' is a matrix, it must contain numbers only !")
		} else {
			# Variables declaration
			KeysR		<- Ret$Input$Variables$Keys						# Keys read
			KeysC		<- vector(length=4)								# Keys computed from data
		
			nbN			<- Ret$Input$Variables$nbN						# Number of nodes
			nbPc		<- Ret$Input$Variables$nbPc                   # Number of conducted perturbations
			nbBase		<- Ret$Input$Variables$nbBase                 # Number of basal columns
			MatD		<- Ret$Input$Variables$MatD                   # Matrix (2*(Xi,j-Xi) / (Xi,j+Xi) or Xi,j-Xi) transposed and coordinates of the perturbations vs. parameters.
			MatExp		<- Ret$Input$InputPar$MatExp					# "Expression Matrix", see the document "Projet de mémoire de thèse - 1° partie"
			
			# Calculation of the keys
			KeysC[1]	<-	 3*nbN +  7*(nbPc+nbBase)
			KeysC[2]	<-	19*nbN + 37*(nbPc+nbBase)
			KeysC[3]	<-	sum(abs(MatD[ , ]))
			KeysC[4]	<-	sum(abs(MatExp[1, ])) + sum(abs(MatExp[ ,1]))
		
			if (KeysC[1] != KeysR[1] || KeysC[2] != KeysR[2] || KeysC[3] != KeysR[3] || KeysC[4] != KeysR[4])
				return ("Ret is NOT a valid return from MRARegress !")
		}

		# Test 'File'
		if (! is.null(File) && ! is.character(File))
			return ("File must be NULL or a string !")
		
		# Test threshold value
		if (! is.numeric(Thr))
			return ("Thr must be a number !")
		if (Thr <= 0)
			return ("Thr must be a strictly positive number !")
			
		return (NULL)			# No error detected
	},		# expr
	
	warning = function (e) {
		message ("DrawGraphML : check input parameters : Warning detected !")
		print(e)	
		return ("Warning")
	},		# warning
	
	error = function (e) {
		message ("DrawGraphML : check input parameters : Error detected !")
		print(e)
	}		# error
  )			# tryCatch
  
  return ("Error")
}		# CheckInputDataDGML
